name: Daily Odds Scraper

on:
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches:
      - main
      
  # Run at 8:00 AM Eastern Time (ET) every day
  # This is 12:00 UTC (8:00 AM ET is UTC-4 during daylight saving time, UTC-5 during standard time)
  schedule:
    - cron: '0 12 * * *'

jobs:
  scrape_odds:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libxkbcommon-x11-0 libgtk-3-0 libasound2 libx11-xcb1 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libglib2.0-0 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libdbus-1-3 libxcb1 libxcursor1 libxi6 libxtst6 libnss3 libasound2 libpangocairo-1.0-0 libcairo-gobject2 libatk1.0-0 libgtk-3-0
          
      - name: Install Playwright
        run: |
          pip install playwright==1.40.0
          python -m playwright install firefox --with-deps
          
      - name: Run odds scraper
        run: python odds_new.py
