name: Daily Odds Scraper

on:
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches:
      - main
      
  # Run at 8:00 AM Eastern Time (ET) every day
  # This is 12:00 UTC (8:00 AM ET is UTC-4 during daylight saving time, UTC-5 during standard time)
  schedule:
    - cron: '0 12 * * *'

jobs:
  scrape_odds:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1
        
      - name: Install Playwright browsers
        run: python -m playwright install firefox
          
      - name: Run odds scraper
        run: python odds_new.py
