name: Daily Odds Scraper

on:
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches:
      - main
      
  # Run at 9:00 AM European time (Central European Time) every day
  # This is 8:00 UTC (9:00 AM CET is UTC+1 during standard time, UTC+2 during summer time)
  schedule:
    - cron: '0 8 * * *'

jobs:
  scrape_odds:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.40.0-jammy
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Fix for running Firefox in container
      - name: Setup user for Firefox
        run: |
          # Create a new user to run Firefox
          groupadd -r pwuser && useradd -r -g pwuser -G audio,video pwuser
          mkdir -p /home/pwuser
          chown -R pwuser:pwuser /home/pwuser
          # Make the project directory accessible to pwuser
          chown -R pwuser:pwuser .
          
      - name: Run odds scraper
        run: |
          # Run Firefox as non-root user
          su pwuser -c 'python odds_new.py'
