name: Daily Odds Scraper

on:
  schedule:
    # Run at 8:00 AM Eastern Time (ET) every day
    # This is 12:00 UTC (8:00 AM ET is UTC-4 during daylight saving time, UTC-5 during standard time)
    - cron: '0 12 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape_odds:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Playwright browsers
        run: |
          python -m playwright install firefox
          
      - name: Run odds scraper
        run: |
          # Run the script and redirect output to a log file
          python odds_new.py > odds_scraper_log.txt 2>&1
        # Using hardcoded credentials directly as requested
        
      - name: Upload logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: odds-scraper-logs
          path: odds_scraper_log.txt
          retention-days: 7
