name: Daily Odds Scraper

on:
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches:
      - main
      
  # Run at 8:00 AM Eastern Time (ET) every day
  # This is 12:00 UTC (8:00 AM ET is UTC-4 during daylight saving time, UTC-5 during standard time)
  schedule:
    - cron: '0 12 * * *'

jobs:
  scrape_odds:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.40.0-jammy
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run odds scraper
        run: python odds_new.py
