name: Simple Test Workflow

# Run on any push to any branch
on: push

jobs:
  test_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run a simple command
        run: echo "Hello, GitHub Actions!"
